### PR TITLE
Add cassert

### PR DESCRIPTION
**Pull request by adamvm**
Add cassert to handle assertion in main.cpp

### CODE REVIEW

**Comment by FreddieChopin** [comment]
Please use `distortos/assert.h` instead of the standard header, as the one which I added has better handling of unused variables (which causes a warning when assertions are disabled).

BTW - which compiler are you using if you see an error here? It works for me fine with the most recent bleeding-edge-toolchain (gcc 9.3.0).

**Comment by adamvm** [comment]
```
[ 98%] Building CXX object CMakeFiles/STM32F7-ETH-LAN8720A-lwIP-MQTT.dir/main.cpp.o
/home/adi/dev/distortec/STM32F7-ETH-LAN8720A-lwIP-MQTT/main.cpp: In function 'void {anonymous}::mqttClientConnectionCallback(mqtt_client_t*, void*, mqtt_connection_status_t)':
/home/adi/dev/distortec/STM32F7-ETH-LAN8720A-lwIP-MQTT/main.cpp:106:2: error: 'assert' was not declared in this scope
  106 |  assert(argument != nullptr);
      |  ^~~~~~
/home/adi/dev/distortec/STM32F7-ETH-LAN8720A-lwIP-MQTT/main.cpp:34:1: note: 'assert' is defined in header '<cassert>'; did you forget to '#include <cassert>'?
   33 | #include <optional>
  +++ |+#include <cassert>
   34 | //#include <cassert>
```

```
$ c++ --version
c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
```

**Comment by FreddieChopin** [comment]
> $ c++ --version
> c++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0

This is FOR SURE not the compiler you are using to build the project, because this project will never compile when using a desktop-targeting compiler instead of arm-none-eabi-g++.

**Comment by FreddieChopin** [comment]
Merged both commits (squashed them into one), with minor style fixes. Thanks!

**Comment by adamvm** [comment]
```
$ /usr/bin/arm-none-eabi-g++ --version
arm-none-eabi-g++ (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
```

**Comment by FreddieChopin** [comment]
Please note that the ONLY supported and tested compiler for distortos is bleeding-edge-toolchain.
https://github.com/FreddieChopin/bleeding-edge-toolchain
All other compilers will soon or later make the project broken and unusable (either because of non-compatible/non-optimal newlib settings or because c++ exceptions are most-likely NOT fully disabled in such toolchains).

**Pull request closed without merging**
